-- CREATE A MIGRATION ENTRY
INSERT INTO `DB_MIGRATIONS` (`MIGRATION`) VALUES ('20190405_cnr_chat_ban_creation');

-- BEGIN

-- CREATE TABLE
CREATE TABLE IF NOT EXISTS `CHAT_BANS` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(25) DEFAULT NULL,
  `BANNED_BY_ID` int(11) NOT NULL,
  `BANNED_BY` varchar(25) DEFAULT NULL,
  `REASON` varchar(25) DEFAULT NULL,
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;